apiVersion: v1
kind: Template
labels:
  template: gcc630-centos7-builder
metadata:
  annotations:
    description: gcc630-centos7 container
    iconClass: tensorflow
    tags: ai-stack-builder
  name: gcc630-centos7-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: gcc630-centos7
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: gcc630-centos7
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: gcc630-centos7:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: gcc630-centos7
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/goern/AI-Stacks-pipeline.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: stack-images/gcc630-centos7
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master