apiVersion: v1
kind: Template
labels:
  template: tensorflow-centos7-python3-builder
metadata:
  annotations:
    description: tensorflow-centos7-python3 container
    iconClass: tensorflow
    tags: ai-stack-builder
  name: tensorflow-centos7-python3-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: tensorflow-centos7-python3
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: tensorflow-centos7-python3
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: tensorflow-centos7-python3:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: tensorflow-centos7-python3
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/goern/AI-Stacks-pipeline.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: stack-images/tensorflow-centos7+python3
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master