apiVersion: v1
kind: Template
labels:
  template: scikit-image-centos7-python2-builder
metadata:
  annotations:
    description: scikit-image-centos7-python2 container
    iconClass: scikit-image
    tags: ai-stack-builder
  name: scikit-image-centos7-python2-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: scikit-image-centos7-python2
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: scikit-image-centos7-python2
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: scikit-image-centos7-python2:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: scikit-image-centos7-python2
          - name: BUILD_LOGLEVEL
            value: "2"
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/goern/AI-Stacks-pipeline.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: stack-images/scikit-image-centos7+python2
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master