apiVersion: v1
kind: Template
labels:
  template: tensorflow-fedora27-builder
metadata:
  annotations:
    description: tensorflow-fedora27 container
    iconClass: tensorflow
    tags: ai-stack-builder
  name: tensorflow-fedora27-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: tensorflow-fedora27
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: tensorflow-fedora27-test
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: tensorflow-fedora27
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: tensorflow-fedora27:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: tensorflow-fedora27
      type: Docker
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: tensorflow-fedora27-test
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: tensorflow-fedora27-test:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}/tests
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: CONTAINER_NAME
          value: tensorflow-fedora27-test
        - name: BUILD_LOGLEVEL
          value: 2
        from:
          kind: ImageStreamTag
          name: tensorflow-fedora27:${TENSORFLOW_VERSION}
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/goern/AI-Stacks-pipeline.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: stack-images/tensorflow-fedora27
- description: Tensorflow version.
  displayName: Tensorflow version
  name: TENSORFLOW_VERSION
  value: 1.4.1
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master